checks:
    - specification
    - branch-release
    - codevalidator
specification:
    allowed_schemes: ['https']
    allowed_formats: ['uri', 'github']
branch-release:
    pattern: '^v(?:\d|\_|\.)+$'
